# Generated by Django 5.1.4 on 2024-12-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
