# Generated by Django 5.1.4 on 2024-12-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
