# Generated by Django 5.1.4 on 2024-12-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_productimages_product_remove_products_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.size'),
        ),
    ]
