# Generated by Django 5.1.4 on 2025-01-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_products_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='product.size'),
        ),
    ]
