# Generated by Django 5.1.4 on 2025-01-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_review_order_ispaid_order_paidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order_mobile',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
